name: "Deployment pipeline"

on:
  push:
    branches:
      - main

jobs: 
  start_pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: FantasyPL_Test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    env:
      NODE_ENV: test
      PG_PORT: 5432
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}


    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with: 
          node-version: 'latest'
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Build backend
        working-directory: ./backend
        run: npm run build
      - name: Build client
        working-directory: ./client
        run: npm run build
      - name: Run DB migrations
        working-directory: ./backend
        run: npm run migrate:test 
      - name: Test backend 
        working-directory: ./backend
        run: npm test
      - name: Test client
        working-directory: ./client
        run: npm run test